Added template
agilecrm/500apps-public-gtm-convertpath pull request #1
Opened 2021-11-10 07:22 UTC by 500apps-RahulVangari

2021-11-11 02:33 UTC, subramaniyamkolluri commented
video

2021-11-11 02:36 UTC, subramaniyamkolluri requested changes

2021-11-11 02:36 UTC, subramaniyamkolluri commented on README.md
> +[Get Started](https://infinity.500apps.com/convertpath) to build interactive popups in [Convertpath](https://convertpath.com)
ConvertPath

2021-11-11 02:36 UTC, subramaniyamkolluri commented on README.md
> +Adding the Convertpath tag to your website once you're logged in to your account with the container, it's time to add a new tag with the Convertpath tracking code inside it. To do so, follow these st
everywhere

2021-11-11 02:36 UTC, subramaniyamkolluri commented on README.md
> +5. Find the randomly generated Convertpath key for the department in the share script slide bar, copy and place the key in the field provided in the Tag Configuration.
Just say api key

Its in better instructions not share script slide bar

Its not slide, its side

2021-11-11 02:36 UTC, subramaniyamkolluri commented on README.md
> +![alt text](https://infinity.500apps.com/img/pushninja/GTM-Image-1.png)
pushninja?

2021-11-11 02:36 UTC, subramaniyamkolluri commented on template.tpl
> +  "displayName": "Convertpath by 500apps",
everywhere

2021-11-11 07:44 UTC, 500apps-RahulVangari commented on README.md
> +![alt text](https://infinity.500apps.com/img/pushninja/GTM-Image-1.png)
This are same images so using them.

2021-11-11 10:01 UTC, 500apps-RahulVangari commented
> video

video : https://drive.google.com/file/d/13QRDPXa751Y0g4lizxAApF5zXwxzCN_8/view

2021-11-11 13:12 UTC, subramaniyamkolluri commented on README.md
> +![alt text](https://infinity.500apps.com/img/pushninja/GTM-Image-1.png)
why then ninjacapture or botup had different images

2021-11-11 14:48 UTC, 500apps-RahulVangari commented on README.md
> +![alt text](https://infinity.500apps.com/img/pushninja/GTM-Image-1.png)
In botup they are also showing same images but they are using different files.

2021-11-11 14:53 UTC, 500apps-RahulVangari commented on README.md
> +![alt text](https://infinity.500apps.com/img/pushninja/GTM-Image-1.png)
They are showing same images but different files

2021-11-13 03:27 UTC, subramaniyamkolluri commented on README.md
> +5. Find the randomly generated api key for the department in the share script side bar, copy and place the key in the field provided in the Tag Configuration.
remove randomly generated phrase

2021-11-15 05:50 UTC, subramaniyamkolluri requested changes

2021-11-15 05:50 UTC, subramaniyamkolluri commented on README.md
> +5. Find the generated api key for the department in the share script side bar, copy and place the key in the field provided in the Tag Configuration.
User may not know where and how to copy api key. Instead ask him to clik gtm icon instructions and ask him to copy from there

2021-11-15 07:38 UTC, subramaniyamkolluri commented
Manohar. Unable to tag you here. Pl review

2021-11-16 16:17 UTC, agilecrm commented
500apps ConvertPath

2021-11-18 07:22 UTC, 500apps-RahulVangari commented
> 500apps ConvertPath

Sir, Done with changes

2021-11-23 03:42 UTC, agilecrm commented on README.md
> +Get Started with a powerful platform to build a Smart Website Popups software for your website
Better content here

2021-11-23 10:46 UTC, 500apps-RahulVangari commented on README.md
> +Get Started with a powerful platform to build a Smart Website Popups software for your website
Done sir

2021-11-28 03:28 UTC, merged